// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWPxfJ5o5sU1acuplu-tvPYjhtOb_w8JY',
    appId: '1:260184257179:web:f77787c0078ed7b9fd4c3e',
    messagingSenderId: '260184257179',
    projectId: 'fmc-seguridad',
    authDomain: 'fmc-seguridad.firebaseapp.com',
    storageBucket: 'fmc-seguridad.firebasestorage.app',
    measurementId: 'G-CJCTMYQVFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBZi_fREztYVinx3KJngJfi2G4YM7krF0',
    appId: '1:260184257179:android:d0176e90cb904788fd4c3e',
    messagingSenderId: '260184257179',
    projectId: 'fmc-seguridad',
    storageBucket: 'fmc-seguridad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSClx8OXyQI_94FciYa1ZDYkTXvRk6gG0',
    appId: '1:260184257179:ios:51d28b7084d6f9befd4c3e',
    messagingSenderId: '260184257179',
    projectId: 'fmc-seguridad',
    storageBucket: 'fmc-seguridad.firebasestorage.app',
    iosBundleId: 'com.example.p1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSClx8OXyQI_94FciYa1ZDYkTXvRk6gG0',
    appId: '1:260184257179:ios:51d28b7084d6f9befd4c3e',
    messagingSenderId: '260184257179',
    projectId: 'fmc-seguridad',
    storageBucket: 'fmc-seguridad.firebasestorage.app',
    iosBundleId: 'com.example.p1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWPxfJ5o5sU1acuplu-tvPYjhtOb_w8JY',
    appId: '1:260184257179:web:bb1fdd6b06e66f79fd4c3e',
    messagingSenderId: '260184257179',
    projectId: 'fmc-seguridad',
    authDomain: 'fmc-seguridad.firebaseapp.com',
    storageBucket: 'fmc-seguridad.firebasestorage.app',
    measurementId: 'G-FD9WPXV551',
  );
}
